### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by eliaseythorsson** [ProjectMOSAIC/mosaicModel#7]
install.packages("mosaicModel") does not automatically install the package 'mosaic'. If 'mosaic' is not installed, lines 7-8 in the code sequence below, taken from the 'Using mosaicModel' vignette do not run and the following error is displayed: "Error in library(mosiac) : there is no package called ‘mosiac’"

1    library(randomForest)
2    iris_mod_1 <- randomForest(Species ~ Sepal.Length + Petal.Length, data = iris)
3    library(caret)
4    iris_mod_2 <- knn3(Species ~., data = iris, k = 15)
5    mod_plot(iris_mod_1)
6    mod_plot(iris_mod_2, class_level = "setosa")
7    mod_plot(iris_mod_2, ~ Petal.Length + Petal.Width)
8    mod_plot(iris_mod_2, ~ Petal.Length + Petal.Width + Sepal.Width)

**Comment by dtkaplan** [comment]
Again, thanks. I've added `mosaic` to the depends field in the description file.
