### ISSUE TITLE
Example code in description for mod_eval() does not run

### ISSUE THREAD

**Issue by eliaseythorsson** [ProjectMOSAIC/mosaicModel#8]
Example code in description for mod_eval() does not run. The issue is with the mod_eval() function itself (line 3). See error message below. 

1    mod2 <- glm(married == "Married" ~ age + sex * sector,
2              data = mosaicData::CPS85, family = "binomial")
3     mod_eval(mod2, nlevels = 2)
Error in names(tmp) <- NULL : object 'tmp' not found mosaicData

**Comment by dtkaplan** [comment]
Thanks. I've pushed the fix to this.
